### ISSUE TITLE
Only considering solutions containing edge (n-1 -> 0)

### ISSUE THREAD

**Issue by clemy** [vadimkantorov/tsp-rust#1]
Hi,
Thanks for this nice implementation.
It seems that the code only considers solutions containing the edge (n-1 -> 0).
The initial root is set to ..WithEdge(Edge(n - 1, 0)..) without considering to test the corresponding WithoutEdge(..) PartialSolution.
Changing this and adapting IsComplete() should solve this.
Another point found: The printed cost is missing the last (return) edge.

**Comment by vadimkantorov** [comment]
I think this was done in order to force looped solutions, not just paths

Happy that this code is useful to someone :)

**Comment by clemy** [comment]
Thanks for your quick reply. Yes, even if it solves a bit a different problem, I would like to take some ideas for my own implementation of a branch and bound algorithm in Java. I hope this is ok for you?

**Comment by vadimkantorov** [comment]
Of course :) On the side: [2-opt](https://en.wikipedia.org/wiki/2-opt) in practice was much faster (and simpler to implement) for these real-world city-road networks

**Comment by vadimkantorov** [comment]
If you wish, please go ahead to send a PR with the fix for printing the last edge
